2024-03-02 17:06:26 - INFO - Username: admin logged in successfully
2024-03-02 17:06:31 - INFO - Username: admin accessed reserve_parking
2024-03-02 17:06:31 - ERROR - Exception on /reserve_parking [POST]
Traceback (most recent call last):
  File "c:\Users\ellie\OneDrive\Documents\Programming\Python\Level 6\Bookerplay\.venv\Lib\site-packages\flask\app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\ellie\OneDrive\Documents\Programming\Python\Level 6\Bookerplay\.venv\Lib\site-packages\flask\app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\ellie\OneDrive\Documents\Programming\Python\Level 6\Bookerplay\.venv\Lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\ellie\OneDrive\Documents\Programming\Python\Level 6\Bookerplay\.venv\Lib\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\ellie\OneDrive\Documents\Programming\Python\Level 6\Bookerplay\.venv\Lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ellie\OneDrive\Documents\Programming\Python\Level 6\Bookerplay\app\main\routes.py", line 21, in reserve_parking
    reservation = reserve(username=request.form.get("username"),registration=request.form.get("registration"), date=date)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 4, in __init__
  File "c:\Users\ellie\OneDrive\Documents\Programming\Python\Level 6\Bookerplay\.venv\Lib\site-packages\sqlalchemy\orm\state.py", line 566, in _initialize_instance
    with util.safe_reraise():
  File "c:\Users\ellie\OneDrive\Documents\Programming\Python\Level 6\Bookerplay\.venv\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "c:\Users\ellie\OneDrive\Documents\Programming\Python\Level 6\Bookerplay\.venv\Lib\site-packages\sqlalchemy\orm\state.py", line 564, in _initialize_instance
    manager.original_init(*mixed[1:], **kwargs)
  File "C:\Users\ellie\OneDrive\Documents\Programming\Python\Level 6\Bookerplay\app\models\models.py", line 29, in __init__
    self.date = datetime.strptime(date, "%Y-%m-%d").date()  # Convert string to date object
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: strptime() argument 1 must be str, not datetime.date
2024-03-02 17:08:47 - INFO - Username: admin logged in successfully
2024-03-02 17:08:53 - INFO - Username: admin accessed reserve_parking
2024-03-02 17:08:53 - ERROR - Exception on /reserve_parking [POST]
Traceback (most recent call last):
  File "c:\Users\ellie\OneDrive\Documents\Programming\Python\Level 6\Bookerplay\.venv\Lib\site-packages\flask\app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\ellie\OneDrive\Documents\Programming\Python\Level 6\Bookerplay\.venv\Lib\site-packages\flask\app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\ellie\OneDrive\Documents\Programming\Python\Level 6\Bookerplay\.venv\Lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\ellie\OneDrive\Documents\Programming\Python\Level 6\Bookerplay\.venv\Lib\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\ellie\OneDrive\Documents\Programming\Python\Level 6\Bookerplay\.venv\Lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ellie\OneDrive\Documents\Programming\Python\Level 6\Bookerplay\app\main\routes.py", line 21, in reserve_parking
    reservation = reserve(username=request.form.get("username"),registration=request.form.get("registration"), date=date)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 4, in __init__
  File "c:\Users\ellie\OneDrive\Documents\Programming\Python\Level 6\Bookerplay\.venv\Lib\site-packages\sqlalchemy\orm\state.py", line 566, in _initialize_instance
    with util.safe_reraise():
  File "c:\Users\ellie\OneDrive\Documents\Programming\Python\Level 6\Bookerplay\.venv\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "c:\Users\ellie\OneDrive\Documents\Programming\Python\Level 6\Bookerplay\.venv\Lib\site-packages\sqlalchemy\orm\state.py", line 564, in _initialize_instance
    manager.original_init(*mixed[1:], **kwargs)
  File "C:\Users\ellie\OneDrive\Documents\Programming\Python\Level 6\Bookerplay\app\models\models.py", line 33, in __init__
    elif isinstance(date, date):
         ^^^^^^^^^^^^^^^^^^^^^^
TypeError: isinstance() arg 2 must be a type, a tuple of types, or a union
2024-03-02 17:10:34 - INFO - Username: admin logged in successfully
2024-03-02 17:10:40 - INFO - Username: admin accessed reserve_parking
2024-03-02 17:10:40 - INFO - Username: admin created a new booking in reserve_parking
2024-03-02 17:10:41 - INFO - Username: admin accessed reservations
2024-03-02 17:10:49 - INFO - Username: admin logged out
2024-03-02 17:11:29 - INFO - Username: admin logged in successfully
2024-03-02 17:11:33 - INFO - Username: admin accessed reserve_parking
2024-03-02 17:11:33 - INFO - Username: admin created a new booking in reserve_parking
2024-03-02 17:11:34 - ERROR - Error during retrieving reservations: cast() missing 1 required positional argument: 'type_'
Traceback (most recent call last):
  File "C:\Users\ellie\OneDrive\Documents\Programming\Python\Level 6\Bookerplay\app\main\routes.py", line 53, in reservations
    active_reservations = reserve.query.filter(reserve.cancelled == 'N', cast(reserve.date) >= func.current_date()).all()
                                                                         ^^^^^^^^^^^^^^^^^^
TypeError: cast() missing 1 required positional argument: 'type_'
2024-03-02 17:11:36 - ERROR - Error during retrieving reservations: cast() missing 1 required positional argument: 'type_'
Traceback (most recent call last):
  File "C:\Users\ellie\OneDrive\Documents\Programming\Python\Level 6\Bookerplay\app\main\routes.py", line 53, in reservations
    active_reservations = reserve.query.filter(reserve.cancelled == 'N', cast(reserve.date) >= func.current_date()).all()
                                                                         ^^^^^^^^^^^^^^^^^^
TypeError: cast() missing 1 required positional argument: 'type_'
2024-03-02 17:11:59 - INFO - Username: admin logged in successfully
2024-03-02 17:12:00 - INFO - Username: admin accessed reservations
2024-03-02 17:12:37 - INFO - Username: admin logged in successfully
2024-03-02 17:12:39 - INFO - Username: admin accessed reservations
2024-03-02 17:12:50 - INFO - Username: admin accessed reserve_parking
2024-03-02 17:12:50 - INFO - Username: admin created a new booking in reserve_parking
2024-03-02 17:12:55 - INFO - Username: admin logged out
2024-03-02 17:13:04 - INFO - Username: admin logged in successfully
2024-03-02 17:13:05 - INFO - Username: admin accessed reservations
2024-03-02 17:13:11 - INFO - Username: admin logged out
